version: '3'
services:
  db:
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=django_chatgptUser
      - POSTGRES_PASSWORD=django_chatgptPassword
    volumes:
      - django_chatgpt_db_data:/var/lib/postgresql/data
    networks:
      - django_chatgpt_backend_tier
  redis:
    image: redis:latest
    restart: always
    networks:
      - django_chatgpt_backend_tier

  django_chatgpt:
    restart: always
    build: .
    depends_on:
      - db
      - redis
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8009
    environment:
      - DJANGO_COLLECT_STATIC=off
      - DJANGO_MANAGEPY_MIGRATE=off
    links:
      - db:postgres
      - redis
    volumes:
      - .:/app
    ports:
      - "8009:8009"
    expose:
      - "8009"
    networks:
      - django_chatgpt_backend_tier



volumes:
  django_chatgpt_db_data:
    driver: local
  static_volume:
    driver: local


networks:
  django_chatgpt_backend_tier:
    driver: bridge
