version: '3'

services:
  django_chatGPT:
    restart: always
    image: registry.gitlab.com/django_chatGPT/web-service
    command: gunicorn django_chatGPT.wsgi:application --bind 0.0.0.0:8009 --workers 3 --log-level=DEBUG
    env_file: .env
    ports:
      - "8009:8009"
    expose:
      - "8000"
    networks:
    - django_chatGPT_backend_tier

  celery:
    image: registry.gitlab.com/django_chatGPT/web-service
    command: celery -A django_chatGPT worker -l info
    env_file: .env
    restart: unless-stopped
    networks:
      - django_chatGPT_backend_tier

  nginx:
    image: registry.gitlab.com/classmate2/web-service/nginx
    depends_on:
      - django_chatGPT
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./logs/Nginx:/var/log/nginx/
    networks:
      - django_chatGPT_backend_tier

volumes:
  static_volume:
    driver: local

networks:
  django_chatGPT_backend_tier:
    driver: bridge
